# Generated by Django 5.1.2 on 2024-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamieszkanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=60)),
                ('ulica', models.CharField(max_length=60)),
                ('numer_domu', models.IntegerField()),
                ('numer_mieszkania', models.IntegerField(blank=True, null=True)),
                ('kod_pocztowy', models.IntegerField()),
            ],
        ),
    ]
