# Generated by Django 5.1.2 on 2024-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
