# Generated by Django 5.1.2 on 2024-11-03 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_zamieszkanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamieszkanie',
            name='kod_pocztowy',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_postal_code', message='podaj kod pocztowy w formacie xx-xxx, np. 02-987.', regex='^\\d{2}-\\d{3}$')]),
        ),
    ]
