# Generated by Django 5.1.2 on 2025-01-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_person_pseudonim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(max_length=60),
        ),
    ]
