# Generated by Django 5.1.2 on 2025-01-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stanowisko_osoba'),
        ('myapp', '0008_alter_osoba_data_dodania'),
    ]

    operations = [
    ]
