# Generated by Django 5.1.2 on 2025-01-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_person_other_owner', 'pozwala zobaczyc modele osoba innych wlascicieli')]},
        ),
    ]
